apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ddp-training
spec:
  serviceName: "ddp-master"
  replicas: 4
  selector:
    matchLabels:
      app: ddp-training
  template:
    metadata:
      labels:
        app: ddp-training
    spec:
      containers:
      - name: ddp-container
        image: fortypercent/ddp-training-cpu:v7.0
        env:
        - name: WORLD_SIZE
          value: "4"
        - name: RANK
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MASTER_ADDR
          value: "ddp-master"
        - name: MASTER_PORT
          value: "8888"
        ports:
        - containerPort: 8888
        command: ["/bin/sh", "-c", "tail -f /dev/null & python train_ddp.py & wait"]
---
apiVersion: v1
kind: Service
metadata:
  name: ddp-master
spec:
  selector:
    app: ddp-training
  ports:
  - port: 8888
    targetPort: 8888
