apiVersion: kubeflow.org/v1
kind: PyTorchJob
metadata:
  name: pytorchjob-example
  namespace: kubeflow
spec:
  pytorchReplicaSpecs:
    Worker:
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          initContainers:
          - name: init-mydb
            image: fortypercent/init:v0.1.8
            command: ['sh', '-c',  'sleep 100']
          containers:
          - name: pytorch
            image: pytorch/pytorch:latest
            command: ["/bin/sh", "-c"]
            args:
            - |
              echo "Preparing to run the training script..." && sleep 60
