apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: "fortypercent/init:v1.0"
    command: ["sleep"]
    args: ["3600"] # 使 Pod 保持运行状态 1 小时
    volumeMounts:
    - mountPath: "/test/"
      name: pvc-volume
  volumes:
  - name: pvc-volume
    persistentVolumeClaim:
      claimName: task-manager-pvc
